### ISSUE TITLE
Add a new fluid

### ISSUE THREAD

**Issue by sdaix** [thorade/HelmholtzMedia#42]
Hello,

I want to add a new helmholtz media like hydrogen.
I have find these properties in google and I want create a new media.
https://tsapps.nist.gov/publication/get_pdf.cfm?pub_id=832374

I don't understand how could I do this ?
Can you help me ? 

Thank you

**Comment by thorade** [comment]
Great! Happy to help you with it, until it is done.
The definition of fluids happens here:
https://github.com/thorade/HelmholtzMedia/tree/master/HelmholtzMedia/HelmholtzFluids
For example, the coefficients for Ethanol are in this file:
https://github.com/thorade/HelmholtzMedia/blob/master/HelmholtzMedia/HelmholtzFluids/Ethanol/package.mo

As a start, you can just copy any of the fluids, then start adding the correct coefficients.
These coefficients can be taken from the original publication, or from CoolProp, or from RefProp. The easiest is to take it from RefProp - do you have it installed and a license? In the installation directory, you can find .fld files, these can be opened with any text editor. 

Do you know how to use Github, git, Forking, Pull Requests?

**Comment by sdaix** [comment]
I am sorry
I am beginner on github (also on oenmodelica). 
No I have not access at refprop directly. But I access at these fld file by fluent database software.

I don't retrieve the same coefficient that my fld file for your helium for example
[hydrogen.zip](https://github.com/thorade/HelmholtzMedia/files/6169981/hydrogen.zip)

If it is not good place to discuss this, don't hesitate to advice me 

Thank you for your help
Steven

**Comment by sdaix** [comment]
Hello

I am some difficulties to code the right viscosity or thermal conductivity from fld file.
I can send you the new file package for hydrogen and fld file if you want. (I can't add these files inside this post)

Steven``

**Comment by tbeu** [comment]
> I can't add these files inside this post

You can add them as zipped archive here.

**Comment by thorade** [comment]
Please do not add fld files here, they are part of RefProp and should not be shared.
Your own files can be shard of course, and I will write down how to do it in a few minutes. 
The main steps are:

- Make a fork of the repository
- Clone the fork to your local computer
- Do the changes, start adding new fluid, edit files
- Commit the changes (Locally)
- Push the changes to your fork
- Then make a Pull Request (PR)
- I will review the changes, and if it looks good, accept the PR

**Comment by thorade** [comment]
The transport properties (viscosity, thermal conductivity) are usually more difficult to add than the equation of state, and they partly depend on the equation of state. So, as first step, you have to get the equation of state implemented correctly, and then once that is done and tested, do the transport properties.
Some special fluids do not use any of the general forms for transport properties, and if that is the case for hydrogen, you would have to add the full correlation, and not just some coefficients. You can see helium as an example.

**Comment by thorade** [comment]
Here are the main steps for collaborating on an open-source repository on github:

- Make a [fork](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/working-with-forks) of the repository
- Clone the fork to your local computer
- Do the changes, start adding new fluid, edit files
- Commit the changes (Locally)
- Push the changes to your fork
- Then make a [Pull Request (PR)](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork)
- I will [review](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/reviewing-changes-in-pull-requests) the changes, and if it looks good, accept the PR, and then your code is integrated in this repository

**Comment by thorade** [comment]
Please also see #43 for more fluids

**Comment by thorade** [comment]
Closing this for now, happy to reopen later and continue discussion
