### ISSUE TITLE
Error using Ammonia Properties

### ISSUE THREAD

**Issue by mww1990** [thorade/HelmholtzMedia#44]
Hello,

I am trying to use a Version for Ammonia someone posted here:
https://www.openmodelica.org/forum/user-posts/7470-ctg

When using it in my model, I get this error:

[HelmholtzMedia.HelmholtzFluids.Ammonia: 17:3-40:44]: An element with name fluidConstantsAmmonia is already declared in this scope.

[Modelica.Fluid.Interfaces: 20:5-21:69]: Class Medium.ExtraProperty not found in scope FluidPort.

-Using Butane and other Media of the Helmholtz Media works fine with my model..
-Simulating MediaTestModels with Ammonia works fine too..

Does any1 has an idea?

Greetz

**Comment by thorade** [comment]
Hi,
I assume this is somewhere in your code, so to really answer it, I would need a small example that reproduces this error. Did you read the error message and check whether the variable fluidConstantsAmmonia is declared twice?

The link you have given is pointing to all posts by CTG in the OpenModelica forum, so I assume you are using his library HelmholtzCool, which is also linked in #43

**Comment by thorade** [comment]
I think I cannot do much here, this is too little information
