### ISSUE TITLE
Linux compatibility

### ISSUE THREAD

**Issue by jlaing1007** [thorade/HelmholtzMedia#47]
Is this library compatible with Linux?  I've unsuccessfully attempted to run HelmholtzMedia examples using OMEdit 1.17.0 MSL 3.2.3 on my Linux virtual machine.  I've verified that it runs on Windows, but am unsure what the difference is that is causing issues.  Thanks.

**Example error window:**
**[1] 09:38:39 Translation Error**
[HelmholtzMedia.Interfaces.PartialHelmholtzMedium.Ancillary.saturationPressure_T: 13:3-13:80]: Variable ancillaryCoefficients.pressureSaturation not found in scope Modelica.Fluid.Sources.Boundary_pT$boundary1.Medium.Ancillary.saturationPressure_T.

**[2] 09:38:39 Translation Error**
[HelmholtzMedia.Interfaces.PartialHelmholtzMedium: 571:9-571:52]: Variable sat.liq.d not found in scope Modelica.Fluid.Sources.Boundary_pT$boundary1.Medium.setState_pTX.

**[3] 09:38:39 Translation Error**
[HelmholtzMedia.Interfaces.PartialHelmholtzMedium.EoS.f_i: 9:3-9:64]: Variable helmholtzCoefficients.idealLog not found in scope Modelica.Fluid.Sources.Boundary_pT$boundary1.Medium.EoS.f_i.

**[4] 09:38:39 Translation Error**
[HelmholtzMedia.Interfaces.PartialHelmholtzMedium.EoS.setHelmholtzDerivsSecond: 15:3-15:41]: Class f_i not found in scope Modelica.Fluid.Sources.Boundary_pT$boundary1.Medium.EoS.setHelmholtzDerivsSecond (looking for a function or record).

**[5] 09:38:39 Translation Error**
[HelmholtzMedia.Interfaces.PartialHelmholtzMedium.density_ph_state: 2:1-17:21]: Function .Modelica.Fluid.Sources.Boundary_pT$boundary1.Medium.density_ph_der not found in scope Modelica.Fluid.Sources.Boundary_pT$boundary1.Medium.

**[6] 09:38:40 Translation Error**
[HelmholtzMedia.Interfaces.PartialHelmholtzMedium: 732:5-732:62]: Variable helmholtzCoefficients.useLineSearch not found in scope Modelica.Fluid.Sources.Boundary_pT$boundary1.Medium.setState_phX.

**[7] 09:38:40 Translation Error**
[HelmholtzMedia.Interfaces.PartialHelmholtzMedium: 1637:5-1637:96]: Variable sat.vap.s not found in scope Modelica.Fluid.Sources.Boundary_pT$boundary1.Medium.saturationTemperature_derp_sat.

**[8] 09:38:40 Translation Error**
[HelmholtzMedia.Interfaces.PartialHelmholtzMedium.temperature_ph_state: 2:1-18:25]: Function .Modelica.Fluid.Sources.Boundary_pT$boundary1.Medium.temperature_ph_der not found in scope Modelica.Fluid.Sources.Boundary_pT$boundary1.Medium.

**[9] 09:38:40 Translation Error**
[HelmholtzMedia.Interfaces.PartialHelmholtzMedium.Ancillary.dewDensity_T: 9:3-9:78]: Variable ancillaryCoefficients.densityVaporModel not found in scope Modelica.Fluid.Sources.Boundary_pT$boundary1.Medium.Ancillary.dewDensity_T.

**[10] 09:38:40 Translation Error**
[HelmholtzMedia.Interfaces.PartialHelmholtzMedium.Ancillary.bubbleDensity_T: 9:3-9:81]: Variable ancillaryCoefficients.densityLiquidModel not found in scope Modelica.Fluid.Sources.Boundary_pT$boundary1.Medium.Ancillary.bubbleDensity_T.

**[11] 09:38:40 Translation Error**
[HelmholtzMedia.Interfaces.PartialHelmholtzMedium.Ancillary.saturationTemperature_p: 16:3-16:80]: Variable ancillaryCoefficients.pressureSaturation not found in scope Modelica.Fluid.Sources.Boundary_pT$boundary1.Medium.Ancillary.saturationTemperature_p.

**[12] 09:38:40 Translation Error**
Error occurred while flattening model HelmholtzMedia.Examples.BranchingDynamicPipes

**Comment by thorade** [comment]
Hi, 
this library is pure Modelica code, and should be entirely portable. I have used it on a real Ubuntu machine, on a VirtualBox, and OpenModelica team is running regression testing on Linux.
So I am pretty sure this is not due to Windows/Linux, but to something else. If you use an unmodified clone, or fresh zip download, do the examples work for you? 
It should not make a difference, but you could also update OpenModelica to the latest version, there is at least one release after 1.17.

**Comment by jlaing1007** [comment]
@thorade I appreciate for the quick response.  I agree that it should be portable, and didn't anticipate any issues.  Just cloned a fresh copy of the library and am seeing the same issues; predominantly getting 'not found in scope' error messages for every example.

I just wanted to double check that these issues weren't os related.  I'll continue to wrestle with it. Thanks.

**Comment by thorade** [comment]
Does this happen for all examples or just some?
Are you able to simulate examples from Modelica Standard library?

**Comment by jlaing1007** [comment]
All examples fail with a 'not found in scope' error except for the following:

HelmholtzMedia.Examples.ConvergenceTest.SinglePhase_setState_b_Water
HelmholtzMedia.Examples.Validation.CheckDerivativesWater

The above examples work simply because the medium package used is Modelica.Media.Water.StandardWater, rather than a HelmholtzMedia fluid.  Also, MSL Fluids examples work just fine.

**Comment by thorade** [comment]
Another idea, are you maybe using the old frontend instead of new frontend?
Could you please also try with OpenModelica 1.18?

**Comment by jlaing1007** [comment]
Yup, rookie mistake.  I had 'Enable old frontend for code generation' toggled in the Simulation Setup > Translation Flags tab.  So far, examples seem to be running; I will test all of them now.  Still using OMEdit 1.17.0 with MSL 3.2.3 and it appears to be working just fine.  If any more issues arise I will post them here.  Otherwise, this issue can be resolved.

I appreciate the help, and the timely responses! Best.
