### ISSUE TITLE
TwoPhase_setState fails on Openmodelica 1.18

### ISSUE THREAD

**Issue by bilderbuchi** [thorade/HelmholtzMedia#48]
We've encountered a bug that is also present in HelmholtzMedia.Examples.ConvergenceTest.TwoPhase_setState. See also #39, but I didn't want to pollute that one with details.

TwoPhase_setState fails in Openmodelica 1.18 (NF) on Windows 10 using either current HelmHoltzMedia master (18ff552ace69672034af2bc8466afef6c374a98a) and MSL 3.2.3 or current msl4update (20bd884063abab2d9453b65ebf8e10d1c1859735) and MSL 4.0.0

The error also happens on the [OM 1.18 test server](https://libraries.openmodelica.org/branches/v1.18/HelmholtzMedia/files/HelmholtzMedia_HelmholtzMedia.Examples.ConvergenceTest.TwoPhase_setState.sim) (also currently on the OM master): 
```
Regular simulation: ./HelmholtzMedia_HelmholtzMedia.Examples.ConvergenceTest.TwoPhase_setState -abortSlowSimulation -alarm=480 -lv LOG_STATS
LOG_SUCCESS       | info    | The initialization finished successfully without homotopy method.
assert            | debug   | HelmholtzMedia_HelmholtzMedia.Examples.ConvergenceTest.TwoPhase_setState_functions.c:11145: Invalid root: (nan)^(3)
stdout            | warning | Integrator attempt to handle a problem with a called assert.
assert            | debug   | HelmholtzMedia_HelmholtzMedia.Examples.ConvergenceTest.TwoPhase_setState_functions.c:11145: Invalid root: (nan)^(3)
stdout            | warning | Integrator attempt to handle a problem with a called assert.
assert            | debug   | HelmholtzMedia_HelmholtzMedia.Examples.ConvergenceTest.TwoPhase_setState_functions.c:11145: Invalid root: (nan)^(3)
stdout            | info    | model terminate | Simulation terminated by an assert at time: 10.0002
```

The test regressed [at this point](https://libraries.openmodelica.org/branches/history/master/2021-01-12%2022:58:17..2021-01-14%2001:15:22.html) (also cited by @thorade in #39), and I suspect that [this OM commit](https://github.com/OpenModelica/OpenModelica/commit/14d191b423) by @perost could be connected/the cause ([old trac issue](https://trac.openmodelica.org/OpenModelica/ticket/6293) related to that).

The Modelica Specification issue https://github.com/modelica/ModelicaSpecification/issues/2757 is probably connected but does not seem close to resolution.

Now, why all this exposition? 
The error seems to occur, as far as we can tell, in `HelmholtzMedia.Interfaces.PartialHelmholtzMedium.setState_pd`, because 
* [here](https://github.com/thorade/HelmholtzMedia/blob/18ff552ace69672034af2bc8466afef6c374a98a/HelmholtzMedia/Interfaces/PartialHelmholtzMedium/setState_pd.mo#L130) `f.delta` is NaN, with
* `delta` becoming NaN [here](https://github.com/thorade/HelmholtzMedia/blob/18ff552ace69672034af2bc8466afef6c374a98a/HelmholtzMedia/Interfaces/PartialHelmholtzMedium/setState_pd.mo#L21) during record constructions because it seems to see a `d_crit` of 0.
* `d_crit` maybe ends up being 0 [a little above](https://github.com/thorade/HelmholtzMedia/blob/18ff552ace69672034af2bc8466afef6c374a98a/HelmholtzMedia/Interfaces/PartialHelmholtzMedium/setState_pd.mo#L13) when
* Maybe `MM` is 0 [here](https://github.com/thorade/HelmholtzMedia/blob/18ff552ace69672034af2bc8466afef6c374a98a/HelmholtzMedia/Interfaces/PartialHelmholtzMedium/setState_pd.mo#L10).

I'm not sure if those 0s occur because something is off in the ordering of binding equations when the function is evaluated, so a default/uninitialized value of 0.0 is used (hence the suspicion of https://github.com/OpenModelica/OpenModelica/commit/14d191b423 above), or because something wonky happens when looking up `fluidConstants[1].molarMass`.

In any case, the minimal workaround that makes this test (and our internal model) work is to delay the assignment of `f.delta`:
```
protected
  //...
  EoS.HelmholtzDerivs f(d=d);
  //...
algorithm
  f.delta := d/d_crit;
```
This strengthens my suspicion that the ordering of operations could be off in OM.

Questions/remarks:
* Considering the spec issue above, maybe the desired behaviour of this corner of Modelica is not yet fully clear, maybe we should work around/avoid it in the meantime?
* Should I rather report this to OM to fix on their side (e.g. a tweak of https://github.com/OpenModelica/OpenModelica/commit/14d191b423)?
* I'm not competent to assess the wider implications of this workaround, and if this has to be done elsewhere in the library, too. can anybody else contribute?

**Comment by perost** [comment]
After wasting some time implementing my proposal I realized it wasn't actually needed and we already do handle the modifiers, and the issue is actually my previous changes like you said.

The issue is that `d_crit` is used to initialize `f`, but my sorting of the local elements doesn't realize that because it doesn't look at the modifiers. So `d_crit` gets sorted below `f`, which is wrong. I didn't see that at first since we don't print the modifiers in the flat model, but looking at the generated code it's obvious(ish). I will improve the sorting to also take the modifiers into account, that should fix it for real.

**Comment by perost** [comment]
The issue should be fixed once my PR has been merged, the model now simulates successfully at least.

**Comment by thorade** [comment]
Thanks @bilderbuchi and @perost for the analysis. If any changes in the library are needed afterwards, I am also happy to try that. I think I tried to change this part before, and then it started to fail in another tool, but I can try again if needed.

**Comment by bilderbuchi** [comment]
Awesome, thank you for the (very!) quick fix, @perost ! 
I'll check the next CI library job when it becomes available to see how much this has improved things.

**Comment by perost** [comment]
> Awesome, thank you for the (very!) quick fix, @perost ! I'll check the next CI library job when it becomes available to see how much this has improved things (and update #39).

The [report](https://libraries.openmodelica.org/branches/history/master/2021-11-24%2013:33:15..2021-11-25%2011:41:34.html) looks good, a few more models simulate and nothing broke (just some unstable models). The remaining models that don't simulate all fail with similar errors to this issue, so there might still be some issue with how we initialise variables. All the models that broke due to my earlier commit all work now though.

**Comment by bilderbuchi** [comment]
Thanks! I think this can be closed now.

**Comment by thorade** [comment]
Very nice, thank you!

**Comment by bilderbuchi** [comment]
> All the models that broke due to my earlier commit all work now though.

Sorry to disappoint, but I iiuc [the previous commit](https://libraries.openmodelica.org/branches/history/master/2021-01-12%2022:58:17..2021-01-14%2001:15:22.html) broke HelmholtzMedia.Examples.ConvergenceTest.SinglePhase_setState_psine_Tramp and HelmholtzMedia.Examples.ConvergenceTest.TwoPhase_setState [which are still failing](https://libraries.openmodelica.org/branches/master/HelmholtzMedia/HelmholtzMedia.html).

**Comment by perost** [comment]
> > All the models that broke due to my earlier commit all work now though.
> 
> Sorry to disappoint, but I iiuc [the earlier commit (or at least one in that changeset)](https://libraries.openmodelica.org/branches/history/master/2021-01-12%2022:58:17..2021-01-14%2001:15:22.html) broke HelmholtzMedia.Examples.ConvergenceTest.SinglePhase_setState_psine_Tramp and HelmholtzMedia.Examples.ConvergenceTest.TwoPhase_setState [which are still failing](https://libraries.openmodelica.org/branches/master/HelmholtzMedia/HelmholtzMedia.html).

They show up as working for me, but I had to manually refresh the page with F5 for some reason. Maybe you're having the same issue. There should be 5 models still failing during simulation.

**Comment by bilderbuchi** [comment]
> There should be 5 models still failing during simulation.

exactly, and those two are 2 of these 5 from what I see (after even Ctrl-F5). They dropped from simulate->compile in the earlier commit.

**Comment by perost** [comment]
> > There should be 5 models still failing during simulation.
> 
> exactly, and those two are 2 of these 5 from what I see (after even Ctrl-F5). They dropped from simulate->compile in the earlier commit.

The ones I see that are still failing are:
```
HelmholtzMedia.Examples.ConvergenceTest.Ancillary_Saturation 
HelmholtzMedia.Examples.ConvergenceTest.SinglePhase_setState_pramp_Tsine 
HelmholtzMedia.Examples.ConvergenceTest.setSat
HelmholtzMedia.Examples.Validation.Derivatives_SaturationBoundary
HelmholtzMedia.Examples.Validation.idealGasLimit
```
The [simulation log for SinglePhase_setState_psine_Tramp](https://libraries.openmodelica.org/branches/master/HelmholtzMedia/files/HelmholtzMedia_HelmholtzMedia.Examples.ConvergenceTest.SinglePhase_setState_psine_Tramp.sim) shows some limits being violated (though it seems to just be due to floating point precision issues) but the simulation is successful in the end. [TwoPhase_setState](https://libraries.openmodelica.org/branches/master/HelmholtzMedia/files/HelmholtzMedia_HelmholtzMedia.Examples.ConvergenceTest.TwoPhase_setState.sim) on the other hand simulates without any warnings.

**Comment by bilderbuchi** [comment]
`pramp_Tsine` != `psine_Tramp`, `setSat` != `setState` .. my apologies for wasting your time, all good! Clearly, I should stop working for today 😿
